### ISSUE TITLE
The scheduled test does not test stable properly

### ISSUE THREAD

**Issue by matrss** [Open-MSS/MSS#2172]
The scheduled test runs the workflow from develop with the code from develop, but with the container image for stable. This is wrong, it should run the workflow from stable with the code from stable and its corresponding container image instead.

This is not so trivial to fix, because scheduled workflows only run for the default branch. I think the most straight forward approach would be to use workflow_dispatch and trigger a workflow run on stable from a scheduled workflow on develop.

**Comment by rohit2p** [comment]
@matrss can i work on this?

**Comment by matrss** [comment]
Sure. But I just found out that the workflow_dispatch event also only triggers on the default branch of a repository, so what I suggested as a fix would not work unfortunately. I currently don't have a good idea on how to fix this issue, do you have one?

**Comment by matrss** [comment]
Actually, I think I misunderstood the docs. Using workflow_dispatch on a non-default branches workflow should be possible, as long as the same workflow file (as in same name, not necessarily the same content) also exists on the default branch. This is the case in this repo, so I guess we should just try.

**Comment by rohit2p** [comment]
so here is the thing this is what i think i should do for this problem correct me if i am wrong. so the problem is the current scheduled test runs the` testing.yml `workflow from the develop branch, but with the container image for the stable branch. This is incorrect.
so we need to modify the `testing-scheduled.yml `workflow to trigger the` testing-stable.yml` workflow directly, ensuring the stable branch's code and image are used. and for this i am going to delete the entire block of code associated with the` test-stable-scheduled` job.
and add a new job: jobs:
 ```
 trigger_stable_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trigger stable test
        uses: peter-evans/github-dispatch-workflow@v2
        with:
          workflow: testing-stable
          token: ${{ secrets.GITHUB_TOKEN }} 
```
I'll be following the secure approach using either [GitHub App authentication] or [repository secrets] instead of a personal access token.
so my question is what i think i should do is it the correct way. is the code i want to replace with correct ? also when i do this from what branch i should create a new branch?
